### ISSUE TITLE
ng build --prod

### ISSUE THREAD

**Issue by NilsNaegele** [CreativeIT/material-angular-dashboard#29] opened 2019-11-21 16:52 UTC
#### Expected behavior
build the production bundles

#### Actual behavior
ERROR in : Can't bind to 'htmlFor' since it isn't a known property of 'ng-component'.
1. If 'htmlFor' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("[ERROR ->]<ng-component></ng-component>")

#### Steps to reproduce the behavior
ng build --prod

#### Relevant code
clone this repo
```

```

#### Environment description
Angular CLI: 8.2.2
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version        
-----------------------------------------------------------
@angular-devkit/architect         0.802.2        
@angular-devkit/build-angular     0.802.2        
@angular-devkit/build-optimizer   0.802.2        
@angular-devkit/build-webpack     0.802.2        
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.2.3
@angular/cli                      8.2.2
@angular/material                 8.2.3
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2        
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0

**Comment by NilsNaegele** [comment] 2019-12-07 13:30
toggle.compontent.ts
error source: @HostBinding('for')

**Comment by uwe-pichl** [comment] 2020-01-20 11:01
After "fixing" this issue by adding "schemas: [NO_ERRORS_SCHEMA], " to theme.module.ts following errors occur:

![grafik](https://user-images.githubusercontent.com/49986715/72721477-726dbf80-3b7c-11ea-99a3-97686c155388.png)

**Comment by maxwellCatCoder** [comment] 2020-08-04 22:09
Good night. Production mode uses the AoT compiler with a build optimizer by default.
For quick solution go in angular.json file, find "configation" -> "production" and switch "aot" and "buildoptimizer" to false.
![image](https://user-images.githubusercontent.com/60538056/89350127-16056400-d6b8-11ea-9ad7-ae98c5f96c90.png)
We are working on the optimization of our dashboard for AoT compiler.
Please stay tuned for a nice solution.
Best regards, CreativeIT.

**Comment by maxwellCatCoder** [comment] 2020-08-04 22:16
This issue appears to be the duplicate of #27. Please, stay for updates in #27

**Closed as completed by maxwellCatCoder** 2020-08-04 22:16 UTC
